---
title: "Biol4315_lab2_report_SB"
author: "Sarah Bowker"
date: "2025-09-11"
output: html_document
---

# 2. Long read QC summary exercise

# Bash code chunck
# 3. Use conda to install filtlong package
```{bash, eval=FALSE}
conda install filtlong

# 4. Filter the long read fastq file to keep the longest 75% of the sequesnce
filtlong -p 75 ERR1539001.fastq > ./ERR1539001_75filtered.fastq

# 5. Run Sequali on the filtered file
sequali --outdir ./sequali_reports ./ERR1539001_75filtered.fastq


# 6. Brief description of changes after filtration

# N50 is better compred to the non filtered file, it went from 6681 to 7371

# Most reads are longer than 2000 bp, the 1st percentile is at 2424 which is higher than the 25th percentile from the unfiltered file

# The read length histogram is unimodel with a single peak, which is less wide than the unfiltered file but doesn't have the second small peak of smaller length reads the unfiltered file had

# Average Q scores are all above 7 and the lowest is just below 20 whereas the unfiltered file some Q scores went below 10.

# The bese-level quality is relatively flat and does not drop sharply, more flat than the unfiltered file

# this sequence run is of better quality than the unfiltered file and I would use it in down stream analysis

```

# 8. Downloading illumina reads
```{bash, eval=FALSE}

wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR112/040/ERR11203340/ERR11203340_1.fastq.gz
wget -nc ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR112/040/ERR11203340/ERR11203340_2.fastq.gz
```

# 9. Sequence quality code chunck
```{r, eval=FALSE}
qcPbPc <- rqc(path = ".", pattern = "ERR11203340", openBrowser=FALSE)
```

# Sequence quality per base per cycle
```{r, eval=FALSE}
rqcCycleQualityBoxPlot(qcPbPc)

# Quality score drops below 2 in cycle 101 of the first fastq file
```

# Sequence content per base per cycle
```{r, eval=FALSE}
rqcCycleBaseCallsLinePlot(qcPbPc)

# Based on the plot there are no Ns, they stay at zero in all the cycles
```

# frequency plot
```{r, eval=FALSE}
rqcReadFrequencyPlot(qcPbPc)

# Based on the frequency plot most sequences have one read 
```

# 10. Trim reads based on quality scores 
```{r, eval=FALSE}
```
